# Generated by Django 4.2.5 on 2023-09-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dealership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=100)),
                ("car_model", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="car",
            name="model",
        ),
        migrations.AlterField(
            model_name="car",
            name="picture",
            field=models.ImageField(upload_to="car_pictures/"),
        ),
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("birth_day", models.DateField()),
                (
                    "dealer_of",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dealership.brand",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="dealership.brand",
            ),
        ),
    ]
