# Generated by Django 4.2.5 on 2023-09-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealership", "0002_brand_remove_car_model_alter_car_picture_dealer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="car_model",
        ),
        migrations.AddField(
            model_name="car",
            name="car_model",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
