# Generated by Django 4.2.5 on 2023-09-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealership", "0003_remove_brand_car_model_car_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="picture",
            field=models.ImageField(upload_to="media/car_pictures/"),
        ),
    ]
