FROM python:3-alpine

ENV PYTHONDONTWRITEBYTECOCE 1
ENV PYRHONBUFFERED 1

WORKDIR /code

COPY requirements.txt /code/

RUN pip install --upgrade pip  \
    pip install -r requirements.txt

COPY . /code/

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000" ]

#command to run container ---> docker run -d -p 8000:8000  <your image>